//! Runtime installation facts embedded by the final RuntimeHost executable.
//!
//! The CSPRNG build instance ID and target triple are generated by the
//! `paraegox-runtime-host` composition root. They enter this crate only through
//! the executable's fixed startup call, never through process environment,
//! operator configuration, a descriptor, or journal state.

#[cfg(unix)]
use paraegox_kernel::digest::Digest32;
#[cfg(unix)]
use paraegox_runtime_contracts::execution::{CardDefinitionRef, CardImplementationRef};
#[cfg(unix)]
use paraegox_runtime_contracts::installation::{
    RuntimeCompiledInstallationFactsV1, RuntimeInstallationError,
};

#[cfg(unix)]
const REFERENCE_DEFINITION: [u8; 16] = [0xa1; 16];
#[cfg(unix)]
const REFERENCE_IMPLEMENTATION: [u8; 16] = [0xa2; 16];
#[cfg(unix)]
const REFERENCE_EXPORT: [u8; 16] = [0xa3; 16];
#[cfg(unix)]
const REFERENCE_DEFINITION_DIGEST: [u8; 32] = [0xa4; 32];
#[cfg(unix)]
const REFERENCE_FIXTURE_ARTIFACT_DIGEST: [u8; 32] = [0xa5; 32];

/// Immutable facts supplied by the final executable's generated source.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct RuntimeHostEmbeddedBuildMetadataV1 {
    build_instance_id: [u8; 32],
    target_triple: &'static str,
}

impl RuntimeHostEmbeddedBuildMetadataV1 {
    pub(crate) const fn from_final_executable(
        build_instance_id: [u8; 32],
        target_triple: &'static str,
    ) -> Self {
        Self {
            build_instance_id,
            target_triple,
        }
    }

    #[cfg(unix)]
    pub(crate) const fn target_triple(self) -> &'static str {
        self.target_triple
    }
}

/// Returns the fixed fixture table plus final-executable build identity.
#[cfg(unix)]
pub(crate) fn runtime_compiled_installation_facts(
    metadata: RuntimeHostEmbeddedBuildMetadataV1,
) -> Result<RuntimeCompiledInstallationFactsV1, RuntimeInstallationError> {
    RuntimeCompiledInstallationFactsV1::try_new(
        metadata.build_instance_id,
        CardDefinitionRef::from_bytes(REFERENCE_DEFINITION),
        CardImplementationRef::from_bytes(REFERENCE_IMPLEMENTATION),
        REFERENCE_EXPORT,
        Digest32::from_bytes(REFERENCE_DEFINITION_DIGEST),
        Digest32::from_bytes(REFERENCE_FIXTURE_ARTIFACT_DIGEST),
    )
}

#[cfg(test)]
mod tests {
    use paraegox_kernel::digest::Digest32;
    use paraegox_runtime_contracts::installation::InstalledRuntimeArtifactObservationV1;

    use super::{RuntimeHostEmbeddedBuildMetadataV1, runtime_compiled_installation_facts};

    const EXPECTED_REFERENCE_COMPATIBILITY_DIGEST: Digest32 = Digest32::from_bytes([
        0xd4, 0xb0, 0x7f, 0xe4, 0xae, 0x5d, 0x19, 0x2b, 0x69, 0xe6, 0xc7, 0x15, 0xf6, 0x07, 0x98,
        0x8a, 0xb9, 0xeb, 0x6f, 0x2d, 0xd0, 0x49, 0xc4, 0x7d, 0x19, 0xb6, 0xfa, 0x74, 0xae, 0xde,
        0x2b, 0xec,
    ]);

    fn fixture() -> RuntimeHostEmbeddedBuildMetadataV1 {
        RuntimeHostEmbeddedBuildMetadataV1::from_final_executable(
            [0x31; 32],
            "x86_64-unknown-linux-gnu",
        )
    }

    #[test]
    fn final_executable_build_identity_is_nonzero_and_stable() {
        let first = runtime_compiled_installation_facts(fixture())
            .unwrap_or_else(|error| panic!("compiled facts rejected: {error}"));
        let second = runtime_compiled_installation_facts(fixture())
            .unwrap_or_else(|error| panic!("compiled facts rejected on reread: {error}"));
        assert_eq!(first.compiled_build_instance_id(), [0x31; 32]);
        assert_eq!(first, second);
    }

    #[test]
    fn embedded_target_is_accepted_as_a_canonical_artifact_observation() {
        let target = fixture().target_triple();
        assert!(
            InstalledRuntimeArtifactObservationV1::try_new(
                1,
                Digest32::from_bytes([1; 32]),
                target,
            )
            .is_ok(),
            "build-time target was not canonical: {target}"
        );
    }

    #[test]
    fn embedded_fixture_constructs_the_exact_s7_reference_digest() {
        let facts = runtime_compiled_installation_facts(fixture())
            .unwrap_or_else(|error| panic!("compiled facts rejected: {error}"));
        assert_eq!(
            facts
                .compiled_reference_compatibility_digest()
                .unwrap_or_else(|error| panic!("compiled fixture digest failed: {error}")),
            EXPECTED_REFERENCE_COMPATIBILITY_DIGEST
        );
    }

    #[test]
    fn zero_final_executable_build_identity_is_rejected() {
        let zero = RuntimeHostEmbeddedBuildMetadataV1::from_final_executable(
            [0; 32],
            "x86_64-unknown-linux-gnu",
        );
        assert!(runtime_compiled_installation_facts(zero).is_err());
    }
}
