//! RuntimeHost executable dispatch for the S7-E/S7-F control vertical.
//!
//! No arguments preserves the existing idle RuntimeHost process. The versioned
//! commands are deliberately narrow: the release producer emits the descriptor
//! for this exact executable, the install operation is the only producer of the
//! singleton manifest before it initializes the Runtime store, and the Linux
//! bootstrap service consumes exact provisioned key and service identities,
//! while the two explicit offline migration commands advance only one stopped
//! journal payload version at a time after retaining exact read-only evidence.

use core::fmt;
use std::env;
use std::ffi::{OsStr, OsString};
use std::io::{self, Write};
use std::path::PathBuf;

use paraegox_kernel::digest::Digest32;
use paraegox_kernel::identity::{PrincipalRef, RuntimeHostId};
use paraegox_runtime_contracts::apply::{PlanWriterRef, TenureAuthorityRef, TenureKeyRef};
use paraegox_runtime_contracts::provenance::SourceScopeRef;
use paraegox_runtime_contracts::wire::ApplyAuthKeyRef;

use crate::runtime_build_metadata::RuntimeHostEmbeddedBuildMetadataV1;
use crate::runtime_host::{RuntimeHostProcessError, run_runtime_host_process};

#[cfg(any(target_os = "linux", all(test, unix)))]
use crate::runtime_build_metadata::runtime_compiled_installation_facts;
#[cfg(any(target_os = "linux", all(test, unix)))]
use crate::runtime_control_endpoint::{
    RuntimeBootstrapEndpointError, RuntimeManagedFabricServiceDependenciesV1,
    run_runtime_bootstrap_process,
};

#[cfg(unix)]
use crate::runtime_artifact::{PinnedRuntimeArtifactV1, RuntimeArtifactObservationError};
#[cfg(any(target_os = "linux", all(test, unix)))]
use crate::runtime_initializer::{
    RuntimeInitializationError, RuntimeInitializationInputV1, RuntimeInstallationEvidenceV1,
    initialize_runtime_store_after_preflight,
};
#[cfg(any(target_os = "linux", all(test, unix)))]
use crate::runtime_install_files::read_runtime_build_descriptor;
#[cfg(unix)]
use crate::runtime_install_files::{RuntimeInstallArtifactOutput, RuntimeInstallFileError};
#[cfg(any(target_os = "linux", all(test, unix)))]
use crate::runtime_provisioning::{
    RuntimeProvisioningError, RuntimeProvisioningInputV1, RuntimeProvisioningV1,
};
#[cfg(any(target_os = "linux", all(test, unix)))]
use crate::runtime_store::{
    RuntimeInitializerBeginError, RuntimeInitializerPreflight, RuntimeStore,
    RuntimeStoreMigrationDisposition, RuntimeStoreMigrationError,
};
#[cfg(unix)]
use paraegox_runtime_contracts::installation::{
    MAX_INSTALLED_RUNTIME_BUILD_DESCRIPTOR_BYTES, RuntimeInstallationError,
    generate_build_descriptor,
};
#[cfg(any(target_os = "linux", all(test, unix)))]
use paraegox_runtime_contracts::installation::{
    MAX_INSTALLED_RUNTIME_MANIFEST_BYTES, generate_manifest,
};

const RELEASE_DESCRIPTOR_COMMAND: &str = "release-descriptor-v1";
const INSTALL_COMMAND: &str = "install-v1";
const SERVE_BOOTSTRAP_COMMAND: &str = "serve-bootstrap-v1";
const MIGRATE_JOURNAL_V3_TO_V4_COMMAND: &str = "migrate-journal-v3-to-v4-v1";
const MIGRATE_JOURNAL_V4_TO_V5_COMMAND: &str = "migrate-journal-v4-to-v5-v1";

/// Runs the exact RuntimeHost executable mode selected by process arguments.
///
/// An empty argument list starts the existing RuntimeHost process. Unknown,
/// missing, additional, or non-canonical command arguments fail closed before
/// any file or Runtime state mutation. The two metadata arguments are not CLI
/// or configuration inputs: the `paraegox-runtime-host` composition root passes
/// constants generated by its own build script and embedded in that final
/// executable. A different Rust caller necessarily creates a different binary
/// and is not an alternate metadata path for the deployed RuntimeHost artifact.
pub fn run_runtime_host_entrypoint(
    final_executable_build_instance_id: [u8; 32],
    final_executable_target_triple: &'static str,
) -> Result<(), RuntimeHostEntrypointError> {
    let embedded_metadata = RuntimeHostEmbeddedBuildMetadataV1::from_final_executable(
        final_executable_build_instance_id,
        final_executable_target_triple,
    );
    let command = parse_runtime_host_command(env::args_os().skip(1))?;
    match command {
        RuntimeHostCommand::Run => run_runtime_host_process().map_err(Into::into),
        #[cfg(unix)]
        RuntimeHostCommand::ReleaseDescriptor { descriptor_output } => {
            run_release_descriptor(embedded_metadata, descriptor_output)
        }
        #[cfg(any(target_os = "linux", all(test, unix)))]
        RuntimeHostCommand::Install(arguments) => run_install(embedded_metadata, *arguments),
        #[cfg(any(target_os = "linux", all(test, unix)))]
        RuntimeHostCommand::ServeBootstrap(arguments) => {
            run_bootstrap_service(embedded_metadata, *arguments)
        }
        #[cfg(any(target_os = "linux", all(test, unix)))]
        RuntimeHostCommand::MigrateJournalV3ToV4(arguments) => {
            run_journal_v3_to_v4_migration(*arguments)
        }
        #[cfg(any(target_os = "linux", all(test, unix)))]
        RuntimeHostCommand::MigrateJournalV4ToV5(arguments) => {
            run_journal_v4_to_v5_migration(*arguments)
        }
        #[cfg(all(unix, not(target_os = "linux"), not(test)))]
        RuntimeHostCommand::Install(_)
        | RuntimeHostCommand::ServeBootstrap(_)
        | RuntimeHostCommand::MigrateJournalV3ToV4(_)
        | RuntimeHostCommand::MigrateJournalV4ToV5(_) => {
            Err(RuntimeHostEntrypointFailure::UnsupportedPlatform.into())
        }
        #[cfg(not(unix))]
        RuntimeHostCommand::ReleaseDescriptor { .. }
        | RuntimeHostCommand::Install(_)
        | RuntimeHostCommand::ServeBootstrap(_)
        | RuntimeHostCommand::MigrateJournalV3ToV4(_)
        | RuntimeHostCommand::MigrateJournalV4ToV5(_) => {
            Err(RuntimeHostEntrypointFailure::UnsupportedPlatform.into())
        }
    }
}

#[derive(Debug, Eq, PartialEq)]
enum RuntimeHostCommand {
    Run,
    ReleaseDescriptor { descriptor_output: PathBuf },
    Install(Box<RuntimeInstallArgumentsV1>),
    ServeBootstrap(Box<RuntimeBootstrapArgumentsV1>),
    MigrateJournalV3ToV4(Box<RuntimeJournalMigrationArgumentsV1>),
    MigrateJournalV4ToV5(Box<RuntimeJournalMigrationArgumentsV1>),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[cfg(any(target_os = "linux", all(test, unix)))]
enum RuntimeJournalMigrationStep {
    PayloadV3ToV4,
    PayloadV4ToV5,
}

#[derive(Debug, Eq, PartialEq)]
struct RuntimeInstallArgumentsV1 {
    descriptor: PathBuf,
    descriptor_digest: Digest32,
    manifest_output: PathBuf,
    state_directory: PathBuf,
    provisioning: RuntimeProvisioningArgumentsV1,
}

#[derive(Debug, Eq, PartialEq)]
struct RuntimeBootstrapArgumentsV1 {
    state_directory: PathBuf,
    expected_store_instance_id: [u8; 32],
    provisioning: RuntimeProvisioningArgumentsV1,
}

#[derive(Debug, Eq, PartialEq)]
struct RuntimeJournalMigrationArgumentsV1 {
    state_directory: PathBuf,
    evidence_directory: PathBuf,
    expected_store_instance_id: [u8; 32],
    expected_target_fingerprint: Digest32,
    migration_id: [u8; 32],
}

#[derive(Debug, Eq, PartialEq)]
struct RuntimeProvisioningArgumentsV1 {
    socket_path: PathBuf,
    target: RuntimeHostId,
    source_scope: SourceScopeRef,
    writer: PlanWriterRef,
    runtime_principal: PrincipalRef,
    runtime_uid: u32,
    runtime_gid: u32,
    controller_principal: PrincipalRef,
    controller_uid: u32,
    controller_gid: u32,
    controller_request_key_ref: ApplyAuthKeyRef,
    controller_public_key_path: PathBuf,
    runtime_response_key_ref: ApplyAuthKeyRef,
    runtime_response_public_key_path: PathBuf,
    runtime_response_private_seed_path: PathBuf,
    authority_principal: PrincipalRef,
    authority_uid: u32,
    authority_gid: u32,
    tenure_authority_ref: TenureAuthorityRef,
    tenure_key_ref: TenureKeyRef,
    tenure_public_key_path: PathBuf,
}

#[cfg(any(target_os = "linux", all(test, unix)))]
impl From<RuntimeProvisioningArgumentsV1> for RuntimeProvisioningInputV1 {
    fn from(arguments: RuntimeProvisioningArgumentsV1) -> Self {
        Self {
            socket_path: arguments.socket_path,
            target: arguments.target,
            source_scope: arguments.source_scope,
            writer: arguments.writer,
            runtime_principal: arguments.runtime_principal,
            runtime_uid: arguments.runtime_uid,
            runtime_gid: arguments.runtime_gid,
            controller_principal: arguments.controller_principal,
            controller_uid: arguments.controller_uid,
            controller_gid: arguments.controller_gid,
            controller_request_key_ref: arguments.controller_request_key_ref,
            controller_public_key_path: arguments.controller_public_key_path,
            runtime_response_key_ref: arguments.runtime_response_key_ref,
            runtime_response_public_key_path: arguments.runtime_response_public_key_path,
            runtime_response_private_seed_path: arguments.runtime_response_private_seed_path,
            authority_principal: arguments.authority_principal,
            authority_uid: arguments.authority_uid,
            authority_gid: arguments.authority_gid,
            tenure_authority_ref: arguments.tenure_authority_ref,
            tenure_key_ref: arguments.tenure_key_ref,
            tenure_public_key_path: arguments.tenure_public_key_path,
        }
    }
}

fn parse_runtime_host_command(
    mut arguments: impl Iterator<Item = OsString>,
) -> Result<RuntimeHostCommand, RuntimeHostEntrypointError> {
    let Some(command) = arguments.next() else {
        return Ok(RuntimeHostCommand::Run);
    };
    if command == OsStr::new(RELEASE_DESCRIPTOR_COMMAND) {
        let descriptor_output = required_argument(&mut arguments)?;
        reject_additional_arguments(&mut arguments)?;
        return Ok(RuntimeHostCommand::ReleaseDescriptor {
            descriptor_output: PathBuf::from(descriptor_output),
        });
    }
    if command == OsStr::new(INSTALL_COMMAND) {
        let descriptor = PathBuf::from(required_argument(&mut arguments)?);
        let descriptor_digest = parse_digest_argument(required_argument(&mut arguments)?)?;
        let manifest_output = PathBuf::from(required_argument(&mut arguments)?);
        let state_directory = PathBuf::from(required_argument(&mut arguments)?);
        let provisioning = parse_provisioning_arguments(&mut arguments)?;
        reject_additional_arguments(&mut arguments)?;
        return Ok(RuntimeHostCommand::Install(Box::new(
            RuntimeInstallArgumentsV1 {
                descriptor,
                descriptor_digest,
                manifest_output,
                state_directory,
                provisioning,
            },
        )));
    }
    if command == OsStr::new(SERVE_BOOTSTRAP_COMMAND) {
        let state_directory = PathBuf::from(required_argument(&mut arguments)?);
        let expected_store_instance_id = parse_hex_array(required_argument(&mut arguments)?)?;
        let provisioning = parse_provisioning_arguments(&mut arguments)?;
        reject_additional_arguments(&mut arguments)?;
        return Ok(RuntimeHostCommand::ServeBootstrap(Box::new(
            RuntimeBootstrapArgumentsV1 {
                state_directory,
                expected_store_instance_id,
                provisioning,
            },
        )));
    }
    if command == OsStr::new(MIGRATE_JOURNAL_V3_TO_V4_COMMAND) {
        return Ok(RuntimeHostCommand::MigrateJournalV3ToV4(Box::new(
            parse_runtime_journal_migration_arguments(&mut arguments)?,
        )));
    }
    if command == OsStr::new(MIGRATE_JOURNAL_V4_TO_V5_COMMAND) {
        return Ok(RuntimeHostCommand::MigrateJournalV4ToV5(Box::new(
            parse_runtime_journal_migration_arguments(&mut arguments)?,
        )));
    }
    Err(RuntimeHostEntrypointFailure::InvalidArguments.into())
}

fn parse_runtime_journal_migration_arguments(
    arguments: &mut impl Iterator<Item = OsString>,
) -> Result<RuntimeJournalMigrationArgumentsV1, RuntimeHostEntrypointError> {
    let parsed = RuntimeJournalMigrationArgumentsV1 {
        state_directory: PathBuf::from(required_argument(arguments)?),
        evidence_directory: PathBuf::from(required_argument(arguments)?),
        expected_store_instance_id: parse_hex_array(required_argument(arguments)?)?,
        expected_target_fingerprint: parse_digest_argument(required_argument(arguments)?)?,
        migration_id: parse_hex_array(required_argument(arguments)?)?,
    };
    reject_additional_arguments(arguments)?;
    Ok(parsed)
}

fn parse_provisioning_arguments(
    arguments: &mut impl Iterator<Item = OsString>,
) -> Result<RuntimeProvisioningArgumentsV1, RuntimeHostEntrypointError> {
    Ok(RuntimeProvisioningArgumentsV1 {
        socket_path: PathBuf::from(required_argument(arguments)?),
        target: RuntimeHostId::from_bytes(parse_hex_array(required_argument(arguments)?)?),
        source_scope: SourceScopeRef::from_bytes(parse_hex_array(required_argument(arguments)?)?),
        writer: PlanWriterRef::from_bytes(parse_hex_array(required_argument(arguments)?)?),
        runtime_principal: PrincipalRef::from_bytes(parse_hex_array(required_argument(
            arguments,
        )?)?),
        runtime_uid: parse_canonical_u32(required_argument(arguments)?)?,
        runtime_gid: parse_canonical_u32(required_argument(arguments)?)?,
        controller_principal: PrincipalRef::from_bytes(parse_hex_array(required_argument(
            arguments,
        )?)?),
        controller_uid: parse_canonical_u32(required_argument(arguments)?)?,
        controller_gid: parse_canonical_u32(required_argument(arguments)?)?,
        controller_request_key_ref: ApplyAuthKeyRef::from_bytes(parse_hex_array(
            required_argument(arguments)?,
        )?),
        controller_public_key_path: PathBuf::from(required_argument(arguments)?),
        runtime_response_key_ref: ApplyAuthKeyRef::from_bytes(parse_hex_array(required_argument(
            arguments,
        )?)?),
        runtime_response_public_key_path: PathBuf::from(required_argument(arguments)?),
        runtime_response_private_seed_path: PathBuf::from(required_argument(arguments)?),
        authority_principal: PrincipalRef::from_bytes(parse_hex_array(required_argument(
            arguments,
        )?)?),
        authority_uid: parse_canonical_u32(required_argument(arguments)?)?,
        authority_gid: parse_canonical_u32(required_argument(arguments)?)?,
        tenure_authority_ref: TenureAuthorityRef::from_bytes(parse_hex_array(required_argument(
            arguments,
        )?)?),
        tenure_key_ref: TenureKeyRef::from_bytes(parse_hex_array(required_argument(arguments)?)?),
        tenure_public_key_path: PathBuf::from(required_argument(arguments)?),
    })
}

fn required_argument(
    arguments: &mut impl Iterator<Item = OsString>,
) -> Result<OsString, RuntimeHostEntrypointError> {
    arguments
        .next()
        .ok_or_else(|| RuntimeHostEntrypointFailure::InvalidArguments.into())
}

fn reject_additional_arguments(
    arguments: &mut impl Iterator<Item = OsString>,
) -> Result<(), RuntimeHostEntrypointError> {
    if arguments.next().is_some() {
        Err(RuntimeHostEntrypointFailure::InvalidArguments.into())
    } else {
        Ok(())
    }
}

fn parse_digest_argument(argument: OsString) -> Result<Digest32, RuntimeHostEntrypointError> {
    parse_hex_array(argument).map(Digest32::from_bytes)
}

fn parse_hex_array<const N: usize>(
    argument: OsString,
) -> Result<[u8; N], RuntimeHostEntrypointError> {
    let value = argument
        .to_str()
        .ok_or(RuntimeHostEntrypointFailure::InvalidArguments)?;
    if value.len() != N * 2 {
        return Err(RuntimeHostEntrypointFailure::InvalidArguments.into());
    }
    let mut decoded = [0_u8; N];
    for (index, pair) in value.as_bytes().chunks_exact(2).enumerate() {
        decoded[index] = (lower_hex_nibble(pair[0])? << 4) | lower_hex_nibble(pair[1])?;
    }
    Ok(decoded)
}

fn lower_hex_nibble(value: u8) -> Result<u8, RuntimeHostEntrypointError> {
    match value {
        b'0'..=b'9' => Ok(value - b'0'),
        b'a'..=b'f' => Ok(value - b'a' + 10),
        _ => Err(RuntimeHostEntrypointFailure::InvalidArguments.into()),
    }
}

fn parse_canonical_u32(argument: OsString) -> Result<u32, RuntimeHostEntrypointError> {
    let value = argument
        .to_str()
        .ok_or(RuntimeHostEntrypointFailure::InvalidArguments)?;
    if value.is_empty() || !value.bytes().all(|byte| byte.is_ascii_digit()) {
        return Err(RuntimeHostEntrypointFailure::InvalidArguments.into());
    }
    let parsed = value
        .parse::<u32>()
        .map_err(|_| RuntimeHostEntrypointFailure::InvalidArguments)?;
    if parsed.to_string() != value {
        return Err(RuntimeHostEntrypointFailure::InvalidArguments.into());
    }
    Ok(parsed)
}

#[cfg(unix)]
fn run_release_descriptor(
    embedded_metadata: RuntimeHostEmbeddedBuildMetadataV1,
    descriptor_output: PathBuf,
) -> Result<(), RuntimeHostEntrypointError> {
    let artifact = PinnedRuntimeArtifactV1::observe_current_release_build(embedded_metadata)?;
    let descriptor = generate_build_descriptor(artifact.observation(), artifact.compiled_facts())?;
    RuntimeInstallArtifactOutput::preflight(
        &descriptor_output,
        MAX_INSTALLED_RUNTIME_BUILD_DESCRIPTOR_BYTES,
    )?
    .publish_or_verify_exact(descriptor.canonical_wire())?;
    write_stdout_fact(
        "descriptor_digest",
        descriptor.descriptor_digest().as_bytes(),
    )
}

#[cfg(any(target_os = "linux", all(test, unix)))]
fn run_install(
    embedded_metadata: RuntimeHostEmbeddedBuildMetadataV1,
    arguments: RuntimeInstallArgumentsV1,
) -> Result<(), RuntimeHostEntrypointError> {
    let RuntimeInstallArgumentsV1 {
        descriptor,
        descriptor_digest,
        manifest_output,
        state_directory,
        provisioning,
    } = arguments;
    let provisioning = RuntimeProvisioningV1::try_new(provisioning.into())?;
    let descriptor_wire = read_runtime_build_descriptor(&descriptor)?;
    let installer_artifact =
        PinnedRuntimeArtifactV1::observe_current_installed_production(embedded_metadata)?;
    let installed = generate_manifest(
        &descriptor_wire,
        descriptor_digest,
        provisioning.target(),
        installer_artifact.observation(),
        installer_artifact.compiled_facts(),
    )?;

    // The initializer is an independent artifact consumer. It reopens and
    // rehashes the installed executable instead of trusting the installer's
    // observation or echoing the descriptor as compiled-actual evidence.
    let initializer_artifact =
        PinnedRuntimeArtifactV1::observe_current_installed_production(embedded_metadata)?;
    let input = RuntimeInitializationInputV1::try_new(
        RuntimeInstallationEvidenceV1::new(
            installed.descriptor_canonical_wire(),
            installed.descriptor_digest(),
            installed.manifest_canonical_wire(),
            installed.manifest_digest(),
            provisioning.target(),
            initializer_artifact.observation(),
            initializer_artifact.compiled_facts(),
        ),
        &provisioning,
    )?;

    // Both filesystem destinations are proven safe before either is mutated.
    // Publishing the deterministic manifest first makes the multi-output
    // operation retryable if it crashes before the Runtime marker is created.
    let state_preflight = RuntimeInitializerPreflight::open(&state_directory)?;
    let manifest_output = RuntimeInstallArtifactOutput::preflight(
        &manifest_output,
        MAX_INSTALLED_RUNTIME_MANIFEST_BYTES,
    )?;
    manifest_output.publish_or_verify_exact(installed.manifest_canonical_wire())?;
    let receipt = initialize_runtime_store_after_preflight(state_preflight, input)?;

    let mut stdout = io::stdout().lock();
    stdout
        .write_all(b"runtime_install_v1 manifest_digest=")
        .and_then(|()| write_lower_hex(&mut stdout, receipt.manifest_digest().as_bytes()))
        .and_then(|()| stdout.write_all(b" store_instance_id="))
        .and_then(|()| write_lower_hex(&mut stdout, receipt.store_instance_id()))
        .and_then(|()| stdout.write_all(b" initialized_snapshot_digest="))
        .and_then(|()| {
            write_lower_hex(
                &mut stdout,
                receipt.initialized_snapshot_digest().as_bytes(),
            )
        })
        .and_then(|()| stdout.write_all(b"\n"))
        .map_err(|error| RuntimeHostEntrypointFailure::Output(error.kind()).into())
}

#[cfg(any(target_os = "linux", all(test, unix)))]
fn run_bootstrap_service(
    embedded_metadata: RuntimeHostEmbeddedBuildMetadataV1,
    arguments: RuntimeBootstrapArgumentsV1,
) -> Result<(), RuntimeHostEntrypointError> {
    let provisioning = RuntimeProvisioningV1::try_new(arguments.provisioning.into())?;
    let compiled = runtime_compiled_installation_facts(embedded_metadata)?;
    run_runtime_bootstrap_process(
        &arguments.state_directory,
        arguments.expected_store_instance_id,
        compiled,
        provisioning,
        RuntimeManagedFabricServiceDependenciesV1::unavailable(),
    )?;
    Ok(())
}

#[cfg(any(target_os = "linux", all(test, unix)))]
fn run_journal_v3_to_v4_migration(
    arguments: RuntimeJournalMigrationArgumentsV1,
) -> Result<(), RuntimeHostEntrypointError> {
    run_journal_migration(RuntimeJournalMigrationStep::PayloadV3ToV4, arguments)
}

#[cfg(any(target_os = "linux", all(test, unix)))]
fn run_journal_v4_to_v5_migration(
    arguments: RuntimeJournalMigrationArgumentsV1,
) -> Result<(), RuntimeHostEntrypointError> {
    run_journal_migration(RuntimeJournalMigrationStep::PayloadV4ToV5, arguments)
}

#[cfg(any(target_os = "linux", all(test, unix)))]
fn run_journal_migration(
    step: RuntimeJournalMigrationStep,
    arguments: RuntimeJournalMigrationArgumentsV1,
) -> Result<(), RuntimeHostEntrypointError> {
    let outcome = match step {
        RuntimeJournalMigrationStep::PayloadV3ToV4 => RuntimeStore::migrate_payload_v3_offline(
            &arguments.state_directory,
            &arguments.evidence_directory,
            arguments.expected_store_instance_id,
            arguments.expected_target_fingerprint,
            arguments.migration_id,
        ),
        RuntimeJournalMigrationStep::PayloadV4ToV5 => RuntimeStore::migrate_payload_v4_offline(
            &arguments.state_directory,
            &arguments.evidence_directory,
            arguments.expected_store_instance_id,
            arguments.expected_target_fingerprint,
            arguments.migration_id,
        ),
    }?;
    let receipt = outcome.receipt;
    let output = RuntimeJournalMigrationOutputV1 {
        disposition: outcome.disposition,
        migration_id: receipt.migration_id(),
        source_payload_version: receipt.source_payload_version(),
        source_checksum: receipt.source_checksum(),
        source_store_instance_id: receipt.source_store_instance_id(),
        source_target_fingerprint: receipt.source_target_fingerprint(),
        source_sequence: receipt.source_sequence(),
        canonical_receipt: receipt.canonical_wire(),
    };
    let mut stdout = io::stdout().lock();
    write_runtime_journal_migration_output(&mut stdout, output)
        .map_err(|error| RuntimeHostEntrypointFailure::Output(error.kind()).into())
}

#[cfg(any(target_os = "linux", all(test, unix)))]
struct RuntimeJournalMigrationOutputV1<'a> {
    disposition: RuntimeStoreMigrationDisposition,
    migration_id: &'a [u8; 32],
    source_payload_version: u16,
    source_checksum: Digest32,
    source_store_instance_id: &'a [u8; 32],
    source_target_fingerprint: Digest32,
    source_sequence: u64,
    canonical_receipt: &'a [u8],
}

#[cfg(any(target_os = "linux", all(test, unix)))]
fn write_runtime_journal_migration_output(
    output: &mut impl Write,
    facts: RuntimeJournalMigrationOutputV1<'_>,
) -> Result<(), io::Error> {
    let disposition = match facts.disposition {
        RuntimeStoreMigrationDisposition::Migrated => b"migrated".as_slice(),
        RuntimeStoreMigrationDisposition::AlreadyMigrated => b"already_migrated".as_slice(),
    };
    output.write_all(b"runtime_journal_migration_v1 disposition=")?;
    output.write_all(disposition)?;
    output.write_all(b" migration_id=")?;
    write_lower_hex(output, facts.migration_id)?;
    write!(
        output,
        " source_payload_version={}",
        facts.source_payload_version
    )?;
    output.write_all(b" source_checksum=")?;
    write_lower_hex(output, facts.source_checksum.as_bytes())?;
    output.write_all(b" store_instance_id=")?;
    write_lower_hex(output, facts.source_store_instance_id)?;
    output.write_all(b" target_fingerprint=")?;
    write_lower_hex(output, facts.source_target_fingerprint.as_bytes())?;
    write!(output, " source_sequence={}", facts.source_sequence)?;
    output.write_all(b" receipt=")?;
    write_lower_hex(output, facts.canonical_receipt)?;
    output.write_all(b"\n")
}

#[cfg(unix)]
fn write_stdout_fact(name: &str, bytes: &[u8]) -> Result<(), RuntimeHostEntrypointError> {
    let mut stdout = io::stdout().lock();
    stdout
        .write_all(name.as_bytes())
        .and_then(|()| stdout.write_all(b"="))
        .and_then(|()| write_lower_hex(&mut stdout, bytes))
        .and_then(|()| stdout.write_all(b"\n"))
        .map_err(|error| RuntimeHostEntrypointFailure::Output(error.kind()).into())
}

#[cfg(unix)]
fn write_lower_hex(output: &mut impl Write, bytes: &[u8]) -> Result<(), io::Error> {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for byte in bytes {
        output.write_all(&[HEX[usize::from(byte >> 4)], HEX[usize::from(byte & 0x0f)]])?;
    }
    Ok(())
}

#[derive(Debug)]
enum RuntimeHostEntrypointFailure {
    InvalidArguments,
    #[cfg_attr(
        any(target_os = "linux", test),
        expect(dead_code, reason = "Only non-Linux production dispatch reports this")
    )]
    UnsupportedPlatform,
    Host(RuntimeHostProcessError),
    #[cfg(unix)]
    Artifact(RuntimeArtifactObservationError),
    #[cfg(unix)]
    Installation(RuntimeInstallationError),
    #[cfg(unix)]
    InstallFile(RuntimeInstallFileError),
    #[cfg(any(target_os = "linux", all(test, unix)))]
    Initialization(RuntimeInitializationError),
    #[cfg(any(target_os = "linux", all(test, unix)))]
    Provisioning(RuntimeProvisioningError),
    #[cfg(any(target_os = "linux", all(test, unix)))]
    Preflight(RuntimeInitializerBeginError),
    #[cfg(unix)]
    Output(io::ErrorKind),
    #[cfg(any(target_os = "linux", all(test, unix)))]
    Bootstrap(RuntimeBootstrapEndpointError),
    #[cfg(any(target_os = "linux", all(test, unix)))]
    Migration(RuntimeStoreMigrationError),
}

impl fmt::Display for RuntimeHostEntrypointFailure {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidArguments => formatter.write_str("invalid arguments"),
            Self::UnsupportedPlatform => formatter.write_str("unsupported platform"),
            Self::Host(error) => write!(formatter, "RuntimeHost process: {error}"),
            #[cfg(unix)]
            Self::Artifact(error) => write!(formatter, "executable observation: {error}"),
            #[cfg(unix)]
            Self::Installation(error) => write!(formatter, "installation contract: {error}"),
            #[cfg(unix)]
            Self::InstallFile(error) => write!(formatter, "install artifact file: {error}"),
            #[cfg(any(target_os = "linux", all(test, unix)))]
            Self::Initialization(error) => write!(formatter, "Runtime initialization: {error}"),
            #[cfg(any(target_os = "linux", all(test, unix)))]
            Self::Provisioning(error) => write!(formatter, "Runtime provisioning: {error}"),
            #[cfg(any(target_os = "linux", all(test, unix)))]
            Self::Preflight(error) => write!(formatter, "Runtime store preflight: {error}"),
            #[cfg(unix)]
            Self::Output(kind) => write!(formatter, "operator output I/O: {kind:?}"),
            #[cfg(any(target_os = "linux", all(test, unix)))]
            Self::Bootstrap(error) => write!(formatter, "Runtime bootstrap service: {error}"),
            #[cfg(any(target_os = "linux", all(test, unix)))]
            Self::Migration(error) => write!(formatter, "Runtime journal migration: {error}"),
        }
    }
}

/// Opaque fail-closed RuntimeHost executable entrypoint error.
#[derive(Debug)]
pub struct RuntimeHostEntrypointError {
    failure: RuntimeHostEntrypointFailure,
}

impl From<RuntimeHostEntrypointFailure> for RuntimeHostEntrypointError {
    fn from(failure: RuntimeHostEntrypointFailure) -> Self {
        Self { failure }
    }
}

impl From<RuntimeHostProcessError> for RuntimeHostEntrypointError {
    fn from(error: RuntimeHostProcessError) -> Self {
        RuntimeHostEntrypointFailure::Host(error).into()
    }
}

#[cfg(unix)]
impl From<RuntimeArtifactObservationError> for RuntimeHostEntrypointError {
    fn from(error: RuntimeArtifactObservationError) -> Self {
        RuntimeHostEntrypointFailure::Artifact(error).into()
    }
}

#[cfg(unix)]
impl From<RuntimeInstallationError> for RuntimeHostEntrypointError {
    fn from(error: RuntimeInstallationError) -> Self {
        RuntimeHostEntrypointFailure::Installation(error).into()
    }
}

#[cfg(unix)]
impl From<RuntimeInstallFileError> for RuntimeHostEntrypointError {
    fn from(error: RuntimeInstallFileError) -> Self {
        RuntimeHostEntrypointFailure::InstallFile(error).into()
    }
}

#[cfg(any(target_os = "linux", all(test, unix)))]
impl From<RuntimeInitializationError> for RuntimeHostEntrypointError {
    fn from(error: RuntimeInitializationError) -> Self {
        RuntimeHostEntrypointFailure::Initialization(error).into()
    }
}

#[cfg(any(target_os = "linux", all(test, unix)))]
impl From<RuntimeProvisioningError> for RuntimeHostEntrypointError {
    fn from(error: RuntimeProvisioningError) -> Self {
        RuntimeHostEntrypointFailure::Provisioning(error).into()
    }
}

#[cfg(any(target_os = "linux", all(test, unix)))]
impl From<RuntimeInitializerBeginError> for RuntimeHostEntrypointError {
    fn from(error: RuntimeInitializerBeginError) -> Self {
        RuntimeHostEntrypointFailure::Preflight(error).into()
    }
}

#[cfg(any(target_os = "linux", all(test, unix)))]
impl From<RuntimeBootstrapEndpointError> for RuntimeHostEntrypointError {
    fn from(error: RuntimeBootstrapEndpointError) -> Self {
        RuntimeHostEntrypointFailure::Bootstrap(error).into()
    }
}

#[cfg(any(target_os = "linux", all(test, unix)))]
impl From<RuntimeStoreMigrationError> for RuntimeHostEntrypointError {
    fn from(error: RuntimeStoreMigrationError) -> Self {
        RuntimeHostEntrypointFailure::Migration(error).into()
    }
}

impl fmt::Display for RuntimeHostEntrypointError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "RuntimeHost entrypoint failed: {}", self.failure)
    }
}

impl std::error::Error for RuntimeHostEntrypointError {}

#[cfg(test)]
mod tests {
    use nix::unistd::{getegid, geteuid};

    use super::*;

    fn os(value: &str) -> OsString {
        OsString::from(value)
    }

    #[test]
    fn empty_arguments_preserve_the_existing_runtime_process_mode() {
        assert_eq!(
            parse_runtime_host_command(Vec::<OsString>::new().into_iter())
                .unwrap_or_else(|error| panic!("empty command rejected: {error}")),
            RuntimeHostCommand::Run
        );
    }

    #[test]
    fn release_descriptor_command_is_exact_and_versioned() {
        assert_eq!(
            parse_runtime_host_command(
                [os(RELEASE_DESCRIPTOR_COMMAND), os("/tmp/runtime.pxbd")].into_iter()
            )
            .unwrap_or_else(|error| panic!("release command rejected: {error}")),
            RuntimeHostCommand::ReleaseDescriptor {
                descriptor_output: PathBuf::from("/tmp/runtime.pxbd"),
            }
        );
        for arguments in [
            vec![os(RELEASE_DESCRIPTOR_COMMAND)],
            vec![
                os(RELEASE_DESCRIPTOR_COMMAND),
                os("/tmp/runtime.pxbd"),
                os("extra"),
            ],
            vec![os("release-descriptor")],
        ] {
            assert!(parse_runtime_host_command(arguments.into_iter()).is_err());
        }
    }

    #[test]
    fn install_command_rejects_missing_extra_noncanonical_and_wrong_width_fields() {
        let mut valid = vec![
            os(INSTALL_COMMAND),
            os("/tmp/runtime.pxbd"),
            os(&"11".repeat(32)),
            os("/tmp/runtime.pxcm"),
            os("/tmp/runtime-state"),
        ];
        valid.extend(valid_provisioning_arguments());
        assert!(parse_runtime_host_command(valid.clone().into_iter()).is_ok());

        let mut missing = valid.clone();
        missing.pop();
        assert!(parse_runtime_host_command(missing.into_iter()).is_err());
        let mut extra = valid.clone();
        extra.push(os("extra"));
        assert!(parse_runtime_host_command(extra.into_iter()).is_err());
        let mut uppercase = valid.clone();
        uppercase[2] = os(&"AA".repeat(32));
        assert!(parse_runtime_host_command(uppercase.into_iter()).is_err());
        let mut wrong_width = valid;
        wrong_width[6] = os(&"22".repeat(15));
        assert!(parse_runtime_host_command(wrong_width.into_iter()).is_err());
    }

    fn valid_provisioning_arguments() -> Vec<OsString> {
        let runtime_uid = geteuid().as_raw();
        let runtime_gid = getegid().as_raw();
        let controller_uid = distinct_uid(runtime_uid, 1);
        let authority_uid = distinct_uid(runtime_uid, 2);
        vec![
            os("/tmp/runtime-control/bootstrap.sock"),
            os(&"31".repeat(16)),
            os(&"32".repeat(16)),
            os(&"33".repeat(16)),
            os(&"34".repeat(16)),
            os(&runtime_uid.to_string()),
            os(&runtime_gid.to_string()),
            os(&"35".repeat(16)),
            os(&controller_uid.to_string()),
            os(&runtime_gid.to_string()),
            os(&"36".repeat(16)),
            os("/tmp/runtime-keys/controller.pub"),
            os(&"37".repeat(16)),
            os("/tmp/runtime-keys/runtime.pub"),
            os("/tmp/runtime-keys/runtime.seed"),
            os(&"38".repeat(16)),
            os(&authority_uid.to_string()),
            os(&runtime_gid.to_string()),
            os(&"39".repeat(16)),
            os(&"3a".repeat(16)),
            os("/tmp/runtime-keys/authority.pub"),
        ]
    }

    fn distinct_uid(runtime_uid: u32, distance: u32) -> u32 {
        if runtime_uid <= u32::MAX - distance {
            runtime_uid + distance
        } else {
            runtime_uid - distance
        }
    }

    fn valid_bootstrap_command() -> Vec<OsString> {
        let mut command = vec![
            os(SERVE_BOOTSTRAP_COMMAND),
            os("/tmp/runtime-state"),
            os(&"32".repeat(32)),
        ];
        command.extend(valid_provisioning_arguments());
        command
    }

    fn valid_migration_command_for(command: &str) -> Vec<OsString> {
        vec![
            os(command),
            os("/tmp/runtime-state"),
            os("/tmp/runtime-migration-evidence"),
            os(&"41".repeat(32)),
            os(&"42".repeat(32)),
            os(&"43".repeat(32)),
        ]
    }

    fn valid_migration_command() -> Vec<OsString> {
        valid_migration_command_for(MIGRATE_JOURNAL_V3_TO_V4_COMMAND)
    }

    fn valid_v4_to_v5_migration_command() -> Vec<OsString> {
        valid_migration_command_for(MIGRATE_JOURNAL_V4_TO_V5_COMMAND)
    }

    fn expected_migration_arguments() -> RuntimeJournalMigrationArgumentsV1 {
        RuntimeJournalMigrationArgumentsV1 {
            state_directory: PathBuf::from("/tmp/runtime-state"),
            evidence_directory: PathBuf::from("/tmp/runtime-migration-evidence"),
            expected_store_instance_id: [0x41; 32],
            expected_target_fingerprint: Digest32::from_bytes([0x42; 32]),
            migration_id: [0x43; 32],
        }
    }

    #[test]
    fn bootstrap_command_is_exact_versioned_and_uses_key_paths() {
        assert!(matches!(
            parse_runtime_host_command(valid_bootstrap_command().into_iter())
                .unwrap_or_else(|error| panic!("bootstrap command rejected: {error}")),
            RuntimeHostCommand::ServeBootstrap(_)
        ));

        let mut missing = valid_bootstrap_command();
        missing.pop();
        assert!(parse_runtime_host_command(missing.into_iter()).is_err());
        let mut extra = valid_bootstrap_command();
        extra.push(os("extra"));
        assert!(parse_runtime_host_command(extra.into_iter()).is_err());
        let mut uppercase = valid_bootstrap_command();
        uppercase[4] = os(&"AA".repeat(16));
        assert!(parse_runtime_host_command(uppercase.into_iter()).is_err());
        let mut leading_zero_uid = valid_bootstrap_command();
        leading_zero_uid[8] = os("01001");
        assert!(parse_runtime_host_command(leading_zero_uid.into_iter()).is_err());
        let mut signed_gid = valid_bootstrap_command();
        signed_gid[20] = os("+1002");
        assert!(parse_runtime_host_command(signed_gid.into_iter()).is_err());
    }

    #[test]
    fn journal_migration_commands_are_exact_versioned_and_lower_hex_only() {
        assert_eq!(
            parse_runtime_host_command(valid_migration_command().into_iter())
                .unwrap_or_else(|error| panic!("migration command rejected: {error}")),
            RuntimeHostCommand::MigrateJournalV3ToV4(Box::new(expected_migration_arguments()))
        );
        assert_eq!(
            parse_runtime_host_command(valid_v4_to_v5_migration_command().into_iter())
                .unwrap_or_else(|error| panic!("v4-to-v5 migration command rejected: {error}")),
            RuntimeHostCommand::MigrateJournalV4ToV5(Box::new(expected_migration_arguments()))
        );
    }

    fn parse_mutation_sentinel(label: &str) -> (PathBuf, PathBuf) {
        let root = std::env::temp_dir().join(format!(
            "paraegox-runtime-entrypoint-parse-must-not-create-{}-{label}",
            std::process::id(),
        ));
        (root.join("state"), root.join("evidence"))
    }

    fn migration_command_with_paths(
        command: &str,
        state_directory: &std::path::Path,
        evidence_directory: &std::path::Path,
    ) -> Vec<OsString> {
        vec![
            os(command),
            state_directory.as_os_str().to_os_string(),
            evidence_directory.as_os_str().to_os_string(),
            os(&"41".repeat(32)),
            os(&"42".repeat(32)),
            os(&"43".repeat(32)),
        ]
    }

    fn assert_parse_rejected_without_path_mutation(
        arguments: Vec<OsString>,
        state_directory: &std::path::Path,
        evidence_directory: &std::path::Path,
    ) {
        assert!(!state_directory.exists(), "state sentinel already exists");
        assert!(
            !evidence_directory.exists(),
            "evidence sentinel already exists"
        );
        assert!(parse_runtime_host_command(arguments.into_iter()).is_err());
        assert!(!state_directory.exists(), "parser created the state path");
        assert!(
            !evidence_directory.exists(),
            "parser created the evidence path"
        );
    }

    #[test]
    fn both_migration_grammars_reject_unknown_unversioned_missing_additional_and_noncanonical_input_before_mutation()
     {
        for (label, command, unversioned) in [
            (
                "v3-v4",
                MIGRATE_JOURNAL_V3_TO_V4_COMMAND,
                "migrate-journal-v3-to-v4",
            ),
            (
                "v4-v5",
                MIGRATE_JOURNAL_V4_TO_V5_COMMAND,
                "migrate-journal-v4-to-v5",
            ),
        ] {
            let (state_directory, evidence_directory) = parse_mutation_sentinel(label);
            let valid =
                migration_command_with_paths(command, &state_directory, &evidence_directory);

            for prefix_length in 1..valid.len() {
                assert_parse_rejected_without_path_mutation(
                    valid[..prefix_length].to_vec(),
                    &state_directory,
                    &evidence_directory,
                );
            }

            let mut additional = valid.clone();
            additional.push(os("additional"));
            assert_parse_rejected_without_path_mutation(
                additional,
                &state_directory,
                &evidence_directory,
            );

            for field_index in 3..=5 {
                let mut uppercase = valid.clone();
                uppercase[field_index] = os(&"AA".repeat(32));
                assert_parse_rejected_without_path_mutation(
                    uppercase,
                    &state_directory,
                    &evidence_directory,
                );

                let mut wrong_width = valid.clone();
                wrong_width[field_index] = os(&"44".repeat(31));
                assert_parse_rejected_without_path_mutation(
                    wrong_width,
                    &state_directory,
                    &evidence_directory,
                );

                let mut prefixed = valid.clone();
                prefixed[field_index] = os(&format!("0x{}", "44".repeat(32)));
                assert_parse_rejected_without_path_mutation(
                    prefixed,
                    &state_directory,
                    &evidence_directory,
                );
            }

            let mut old_unversioned_name = valid.clone();
            old_unversioned_name[0] = os(unversioned);
            assert_parse_rejected_without_path_mutation(
                old_unversioned_name,
                &state_directory,
                &evidence_directory,
            );

            let mut noncanonical_command_case = valid.clone();
            noncanonical_command_case[0] = os(&command.to_ascii_uppercase());
            assert_parse_rejected_without_path_mutation(
                noncanonical_command_case,
                &state_directory,
                &evidence_directory,
            );

            let mut unknown = valid;
            unknown[0] = os("migrate-journal-v5-to-v6-v1");
            assert_parse_rejected_without_path_mutation(
                unknown,
                &state_directory,
                &evidence_directory,
            );
        }
    }

    fn migration_arguments_for_runner(
        state_directory: PathBuf,
        evidence_directory: PathBuf,
        expected_store_instance_id: [u8; 32],
        expected_target_fingerprint: Digest32,
        migration_id: [u8; 32],
    ) -> RuntimeJournalMigrationArgumentsV1 {
        RuntimeJournalMigrationArgumentsV1 {
            state_directory,
            evidence_directory,
            expected_store_instance_id,
            expected_target_fingerprint,
            migration_id,
        }
    }

    #[test]
    fn both_migration_runners_reject_invalid_identity_inputs_before_opening_paths() {
        for (label, step) in [
            ("runner-v3-v4", RuntimeJournalMigrationStep::PayloadV3ToV4),
            ("runner-v4-v5", RuntimeJournalMigrationStep::PayloadV4ToV5),
        ] {
            let (state_directory, evidence_directory) = parse_mutation_sentinel(label);
            for (expected_error, arguments) in [
                (
                    RuntimeStoreMigrationError::InvalidExpectedStoreInstanceId,
                    migration_arguments_for_runner(
                        state_directory.clone(),
                        evidence_directory.clone(),
                        [0; 32],
                        Digest32::from_bytes([0x42; 32]),
                        [0x43; 32],
                    ),
                ),
                (
                    RuntimeStoreMigrationError::InvalidExpectedTargetFingerprint,
                    migration_arguments_for_runner(
                        state_directory.clone(),
                        evidence_directory.clone(),
                        [0x41; 32],
                        Digest32::from_bytes([0; 32]),
                        [0x43; 32],
                    ),
                ),
                (
                    RuntimeStoreMigrationError::InvalidMigrationId,
                    migration_arguments_for_runner(
                        state_directory.clone(),
                        evidence_directory.clone(),
                        [0x41; 32],
                        Digest32::from_bytes([0x42; 32]),
                        [0; 32],
                    ),
                ),
            ] {
                assert!(!state_directory.exists());
                assert!(!evidence_directory.exists());
                let result = match step {
                    RuntimeJournalMigrationStep::PayloadV3ToV4 => {
                        run_journal_v3_to_v4_migration(arguments)
                    }
                    RuntimeJournalMigrationStep::PayloadV4ToV5 => {
                        run_journal_v4_to_v5_migration(arguments)
                    }
                };
                let error =
                    result.expect_err("invalid migration identity unexpectedly reached the store");
                assert!(matches!(
                    error.failure,
                    RuntimeHostEntrypointFailure::Migration(actual)
                        if core::mem::discriminant(&actual)
                            == core::mem::discriminant(&expected_error)
                ));
                assert!(!state_directory.exists(), "runner created the state path");
                assert!(
                    !evidence_directory.exists(),
                    "runner created the evidence path"
                );
            }
        }
    }

    #[test]
    fn migration_output_keeps_the_v3_v4_wire_and_encodes_v4_v5_disposition_exactly() {
        let migration_id = [0x11; 32];
        let store_instance_id = [0x22; 32];
        let canonical_receipt = [0x55, 0xaa];

        let mut old_output = Vec::new();
        write_runtime_journal_migration_output(
            &mut old_output,
            RuntimeJournalMigrationOutputV1 {
                disposition: RuntimeStoreMigrationDisposition::Migrated,
                migration_id: &migration_id,
                source_payload_version: 3,
                source_checksum: Digest32::from_bytes([0x33; 32]),
                source_store_instance_id: &store_instance_id,
                source_target_fingerprint: Digest32::from_bytes([0x44; 32]),
                source_sequence: 7,
                canonical_receipt: &canonical_receipt,
            },
        )
        .expect("v3-to-v4 output must encode");
        assert_eq!(
            String::from_utf8(old_output).expect("operator output must be UTF-8"),
            format!(
                "runtime_journal_migration_v1 disposition=migrated migration_id={} source_payload_version=3 source_checksum={} store_instance_id={} target_fingerprint={} source_sequence=7 receipt=55aa\n",
                "11".repeat(32),
                "33".repeat(32),
                "22".repeat(32),
                "44".repeat(32),
            ),
        );

        let mut new_output = Vec::new();
        write_runtime_journal_migration_output(
            &mut new_output,
            RuntimeJournalMigrationOutputV1 {
                disposition: RuntimeStoreMigrationDisposition::AlreadyMigrated,
                migration_id: &migration_id,
                source_payload_version: 4,
                source_checksum: Digest32::from_bytes([0x33; 32]),
                source_store_instance_id: &store_instance_id,
                source_target_fingerprint: Digest32::from_bytes([0x44; 32]),
                source_sequence: 8,
                canonical_receipt: &canonical_receipt,
            },
        )
        .expect("v4-to-v5 output must encode");
        assert_eq!(
            String::from_utf8(new_output).expect("operator output must be UTF-8"),
            format!(
                "runtime_journal_migration_v1 disposition=already_migrated migration_id={} source_payload_version=4 source_checksum={} store_instance_id={} target_fingerprint={} source_sequence=8 receipt=55aa\n",
                "11".repeat(32),
                "33".repeat(32),
                "22".repeat(32),
                "44".repeat(32),
            ),
        );
    }

    #[test]
    fn bootstrap_runner_compiles_the_real_composition_path_and_opens_keys_first() {
        let mut command = valid_bootstrap_command();
        command[14] = std::env::temp_dir()
            .join(format!(
                "paraegox-definitely-missing-controller-key-{}",
                std::process::id()
            ))
            .into_os_string();
        let RuntimeHostCommand::ServeBootstrap(arguments) =
            parse_runtime_host_command(command.into_iter())
                .unwrap_or_else(|error| panic!("bootstrap command rejected: {error}"))
        else {
            panic!("bootstrap command selected the wrong mode");
        };
        let error = run_bootstrap_service(
            RuntimeHostEmbeddedBuildMetadataV1::from_final_executable(
                [0x91; 32],
                "x86_64-unknown-linux-gnu",
            ),
            *arguments,
        )
        .expect_err("missing provisioned key unexpectedly started the Runtime service");
        assert!(matches!(
            error.failure,
            RuntimeHostEntrypointFailure::Provisioning(RuntimeProvisioningError::KeyFile(
                io::ErrorKind::NotFound
            ))
        ));
    }
}
